add 00-intro/01-sum solution
js-tasks-ru/vue-20230710_aleksandr322 pull request #1
Opened 2023-07-19 21:46 UTC by guijaffe

test

2023-07-19 21:46 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @ShGKme должен запустить тесты.

2023-07-19 22:49 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-07-20 21:35 UTC, ShGKme requested changes

2023-07-20 21:35 UTC, ShGKme commented on vue-20230710_aleksandr322
В репозиторий склонирована копия этого же репозитория в `git submodule`. Это лишнее.

2023-07-25 05:39 UTC, ShGKme commented
@guijaffe Добрый день, нужна ли помочь с исправлением или объяснением проблемы?

2023-07-27 10:53 UTC, guijaffe commented
> @guijaffe Добрый день, нужна ли помочь с исправлением или объяснением проблемы?

Добрый день. Очень много работы, не успевал глянуть.
Вроде делал всё по инструкции, можно узнать что сделать чтоб исправить проблему?

2023-07-27 15:57 UTC, ShGKme commented
> Вроде делал всё по инструкции, можно узнать что сделать чтоб исправить проблему?

У вас в директорию с репозиторием внутрь ещё раз склонирован этот же репозиторий. Вам нужно просто удалить директорию с репозиторием внутри репозитория и закоммитить это удаление.

2023-07-27 16:13 UTC, guijaffe commented
> 
Ой, произошло случайно. 
Не заметил, исправил)

2023-07-27 16:57 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-07-27 16:59 UTC, ShGKme approved these changes

2023-07-27 16:59 UTC, merged